# generate 20000 deterministic vectors with exact 64-bit reference results
s = 0x12345
def rnd():
    global s
    s = (s * 1103515245 + 12345) & 0xFFFFFFFF
    return s
def s32(x):
    x &= 0xFFFFFFFF
    return x - 0x100000000 if x >= 0x80000000 else x
N = 20000
out = ["/* generated by gen.py: {a, b, mul, div} with div including the guard */",
       "struct vec { int a, b, mul, div; };",
       "static const struct vec V[%d] = {" % N]
for _ in range(N):
    a, b = s32(rnd()), s32(rnd())
    mul = s32((a * b) >> 16)
    aa, bb = abs(a), abs(b)
    if a == -2147483648 or (aa >> 14) >= bb:
        div = -2147483648 if (a ^ b) < 0 else 2147483647
    else:
        q = abs(a << 16) // bb
        div = s32(-q if (a ^ b) < 0 else q)
    out.append("    { %d, %d, %d, %d }," % (a, b, mul, div))
out.append("};")
open("vectors.h", "w").write("\n".join(out) + "\n")
print("vectors.h written")
