#!/usr/bin/env python3
"""Bake the shipped .pico programs into the kernel image, compressed.

They used to go in raw and get mounted into the ramdisk at boot. Now they go
in packed and stay packed until something asks for one, which costs a few
kilobytes less on disk and rather more than that in idle RAM -- an unpacked
tetris is 5.5 KB of ramdisk on a machine that may only have a megabyte of it.

Anything that does not actually get smaller is stored as it is. The entry
carries both sizes, and packed == orig is the flag for "do not run the
decompressor over this", which keeps the kernel side from having to guess.
"""
import sys

sys.path.insert(0, __file__.rsplit("/", 1)[0])
from lzss import compress, decompress


def main():
    if len(sys.argv) < 3:
        sys.exit("usage: mkapps.py <out.c> <file.pico> ...")
    out, files = sys.argv[1], sys.argv[2:]

    blobs = []
    for i, path in enumerate(files):
        raw = open(path, "rb").read()
        packed = compress(raw)
        if len(packed) >= len(raw):
            packed = raw                      # incompressible, ship as is
        else:
            assert decompress(packed, len(raw)) == raw, f"round trip: {path}"
        blobs.append((path.split("/")[-1], f"app{i}_data", packed, len(raw)))

    with open(out, "w") as f:
        f.write("/* generated by tools/mkapps.py -- do not edit */\n")
        f.write('#include "pico.h"\n\n')

        for name, sym, packed, orig in blobs:
            pct = 100 * len(packed) // max(1, orig)
            f.write(f"/* {name}: {orig} bytes packed to {len(packed)} ({pct}%) */\n")
            f.write(f"static const unsigned char {sym}[{len(packed)}] = {{\n")
            for off in range(0, len(packed), 16):
                chunk = packed[off:off + 16]
                f.write("    " + ",".join(f"0x{b:02x}" for b in chunk) + ",\n")
            f.write("};\n\n")

        f.write("void apps_install(void)\n{\n")
        for name, sym, packed, orig in blobs:
            f.write(f'    store_add("{name}", {sym}, {len(packed)}, {orig});\n')
        f.write("}\n")

    raw_total = sum(b[3] for b in blobs)
    packed_total = sum(len(b[2]) for b in blobs)
    saved = raw_total - packed_total
    print(f"  bundled {len(blobs)} programs, {raw_total} -> {packed_total} bytes "
          f"({saved} saved)")


if __name__ == "__main__":
    main()
