#!/usr/bin/env python3
"""Rasterise DejaVu Sans Mono into an 8x16 1-bit font for the framebuffer
console. Generates kernel/font8x16.c."""
from PIL import Image, ImageDraw, ImageFont

W, H = 8, 16
FONT = "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf"

best = None
for size in range(9, 19):
    f = ImageFont.truetype(FONT, size)
    wmax = hmin = hmax = 0
    ok = True
    for c in range(32, 127):
        b = f.getbbox(chr(c))
        wmax = max(wmax, b[2] - b[0])
        hmin = min(hmin, b[1])
        hmax = max(hmax, b[3])
    if wmax <= W and (hmax - hmin) <= H:
        best = (size, f)
print("chosen size:", best[0])
size, font = best

asc = font.getbbox("H")[3]
baseline = (H - (asc + 3)) // 2 + asc

glyphs = []
for code in range(256):
    img = Image.new("L", (W, H), 0)
    d = ImageDraw.Draw(img)
    if 32 <= code < 127:
        ch = chr(code)
        bb = font.getbbox(ch)
        x = (W - (bb[2] - bb[0])) // 2 - bb[0]
        d.text((x, baseline), ch, font=font, fill=255, anchor="ls")
    rows = []
    for y in range(H):
        bits = 0
        for x in range(W):
            if img.getpixel((x, y)) > 110:
                bits |= 0x80 >> x
        rows.append(bits)
    glyphs.append(rows)

with open("kernel/font8x16.c", "w") as fp:
    fp.write("/* 8x16 console font, generated by tools/mkfont.py from\n"
             " * DejaVu Sans Mono (Bitstream Vera derivative licence). */\n")
    fp.write('#include "pico.h"\n\nconst u8 font8x16[256][16] = {\n')
    for code, rows in enumerate(glyphs):
        c = chr(code) if 32 <= code < 127 and code != 92 else " "
        fp.write("    { " + ", ".join(f"0x{r:02X}" for r in rows) + f" }},  /* {code} '{c}' */\n")
    fp.write("};\n")
print("wrote kernel/font8x16.c")

# eyeball a few glyphs
for ch in "AgPico#8":
    print(ch)
    for r in glyphs[ord(ch)]:
        print("  " + "".join("#" if r & (0x80 >> i) else "." for i in range(8)))
