#!/usr/bin/env python3
"""Turn a white-background, single-colour drawing into apps/wallpaper.h.

The desktop wallpaper is a drawing in one blue on white, so it is stored as
16 intensity levels (0 = background, 15 = full blue), cropped to the
drawing and run-length encoded. The desktop scales it to any screen and
maps the 16 levels onto a ramp in its palette.

usage: mkwallpaper.py picture.png apps/wallpaper.h [scale]
"""
import sys
import numpy as np
from PIL import Image

src, out = sys.argv[1], sys.argv[2]
scale = float(sys.argv[3]) if len(sys.argv) > 3 else 0.6

im = Image.open(src).convert('RGB')
a = np.asarray(im).astype(float)
ink = a.min(axis=2) < 225
ys, xs = np.where(ink)
pad = 14
x0, x1 = max(xs.min() - pad, 0), min(xs.max() + pad, a.shape[1] - 1)
y0, y1 = max(ys.min() - pad, 0), min(ys.max() + pad, a.shape[0] - 1)
crop = im.crop((x0, y0, x1 + 1, y1 + 1))
w, h = int(crop.width * scale), int(crop.height * scale)
crop = crop.resize((w, h), Image.LANCZOS)
p = np.asarray(crop).astype(float)

white = np.array([255.0, 255.0, 255.0])
blue = np.array([18.0, 152.0, 253.0])
d = white - blue
t = ((white - p) @ d) / (d @ d)
lv = np.clip(np.rint(t * 15), 0, 15).astype(int)
lv[t < 0.04] = 0

flat = lv.flatten()
rle = []
i = 0
while i < len(flat):
    j = i
    while j < len(flat) and flat[j] == flat[i] and j - i < 255:
        j += 1
    rle += [int(flat[i]), j - i]
    i = j

with open(out, 'w') as f:
    f.write('/* generated by tools/mkwallpaper.py -- do not edit */\n')
    f.write('#define WP_W %d\n#define WP_H %d\n' % (w, h))
    f.write('static const unsigned char wp_rle[%d] = {\n' % len(rle))
    for k in range(0, len(rle), 24):
        f.write(','.join(str(v) for v in rle[k:k + 24]) + ',\n')
    f.write('};\n')
print('wallpaper %dx%d, %d RLE bytes' % (w, h, len(rle)))
